apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: your-image:latest
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: myapp-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-secret
          key: password
  restartPolicy: Never
