apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: your-image:latest
    command: ["echo", "Hello, Kubernetes!"]
  restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-cronjob-container
            image: your-cronjob-image:latest
            command: ["echo", "CronJob executed"]
          restartPolicy: OnFailure
